gems: ['jekyll-lunr-js-search']

# Site settings
title: UC Santa Cruz celebrates 50 years
email: pio@ucsc.edu
description: UC Santa Cruz celebrates 50 years - Events Information | News | Photo Galleries | Timeline
url: 'http://50years.ucsc.edu' # the base hostname & protocol for your site
# baseurl: "" # the subpath of your site, e.g. /blog/

permalink: "/:title/"
timezone: America/Los_Angeles

# Build settings
exclude: ['.gitignore', 's3_website.yml', 'bower.json', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'Guardfile', 'README.md']

markdown: rdiscount
rdiscount:
  extensions: [smart]

encoding: 'utf-8'

twitter_username: ucsc
github_username:  ucsc

lunr_search:
  js: 'js'
  excludes: [rss.xml, atom.xml]


