# Site settings
title: UC Santa Cruz 50th Anniversary
email: pio@ucsc.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000/" # the base hostname & protocol for your site
twitter_username: ucsc
github_username:  ucsc

# Build settings
markdown: kramdown #kramdown

kramdown:
 auto_ids:      true
 footnote_nr:   1
 entity_output: as_char
 toc_levels:    1..6
 smart_quotes:  lsquo,rsquo,ldquo,rdquo
 use_coderay:   false

encoding:     "utf-8"